const SUCCESS = "SUCCESS";
const ERROR = "ERROR";
const DO_GET_COMPANY = "DO_GET_COMPANY";
const DO_GET_DESIGNATION = "DO_GET_DESIGNATION";
const DO_SAVE_COMPANY = "DO_SAVE_COMPANY";
const DO_DELETE_COMPANY = "DO_DELETE_COMPANY";
const DO_CREATE_COMPANY = "DO_CREATE_COMPANY";
const DO_SAVE_BRANCH = "DO_SAVE_BRANCH";
const DO_GET_BRANCH = "DO_GET_BRANCH";
const DO_GET_COUNTRIES = "DO_GET_COUNTRIES";
const DO_GET_STATES = "DO_GET_STATES";
const DO_GET_CITIES = "DO_GET_CITIES";
const TOGGLE_SNACKBAR_OPEN = "TOGGLE_SNACKBAR_OPEN";
const TOGGLE_SNACKBAR_CLOSE = "TOGGLE_SNACKBAR_CLOSE";
const GET_ALL_DEPARTMENT = "GET_ALL_DEPARTMENT";
const DO_DELETE_DEPARTMENT = "DO_DELETE_DEPARTMENT";
const DO_SAVE_DEPARTMENT = "DO_SAVE_DEPARTMENT";
const DO_CREATE_DEPARTMENT = "DO_CREATE_DEPARTMENT";
const DO_DELETE_BRANCH = "DO_DELETE_BRANCH";
const DO_CREATE_BRANCH = "DO_CREATE_BRANCH";
const DO_SAVE_DESIGNATION = "DO_SAVE_DESIGNATION";
const DO_DELETE_DESIGNATION = "DO_DELETE_DESIGNATION";
const DO_CREATE_DESIGNATION = "DO_CREATE_DESIGNATION";

export {
  SUCCESS,
  ERROR,
  DO_GET_COMPANY,
  DO_SAVE_COMPANY,
  DO_DELETE_COMPANY,
  DO_CREATE_COMPANY,
  DO_GET_BRANCH,
  DO_GET_DESIGNATION,
  DO_SAVE_DESIGNATION,
  DO_DELETE_DESIGNATION,
  DO_CREATE_DESIGNATION,
  DO_GET_COUNTRIES,
  DO_GET_STATES,
  DO_GET_CITIES,
  DO_SAVE_BRANCH,
  TOGGLE_SNACKBAR_OPEN,
  TOGGLE_SNACKBAR_CLOSE,
  GET_ALL_DEPARTMENT,
  DO_DELETE_DEPARTMENT,
  DO_SAVE_DEPARTMENT,
  DO_CREATE_DEPARTMENT,
  DO_DELETE_BRANCH,
  DO_CREATE_BRANCH,
};
